config/routes.rb
Mynews::Application.routes.draw do
  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations", :passwords => "users/passwords"}

  resources :categories do
    resources :articles, :only => [:index]
  end

  resources :articles do
    resources :comments, :only => [:new, :create, :destroy]
   
  end

  resources :users
  

  root :to => "articles#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all do |object|
      not object.respond_to?(:visible_to?) or object.visible_to?(user)
    end

    can :update, :all do |object|
      not object.respond_to?(:editable_by?) or object.editable_by?(user)
    end

    can :destroy, :all do |object|
      not object.respond_to?(:deletable_by?) or object.deletable_by?(user)
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :comments
  has_attached_file :picture, :styles => { :medium => "400x400>", :thumb => "100x100>" }
  
  default_scope order("created_at DESC")

  scope :most_commented, reorder("(SELECT COUNT(*) FROM comments WHERE comments.article_id = articles.id) DESC")

  validates_attachment_presence :picture
  validates_attachment_size :picture, :less_than => 5.megabytes
  validates_attachment_content_type :picture, :content_type => ['image/jpeg', 'image/png']
  validates :title, :presence => true, :uniqueness => true, :length => { :minimum => 3, :maximum => 40 }
  validates :body, :presence => true, :uniqueness => true, :length => { :minimum => 40, :maximum => 3000 }
  validates :category, :presence => true
  validates :user, :presence => true
  
  def visible_to?(user)
    true
  end

  def editable_by?(user)
    user.present? and (self.user == user or user.admin?)
  end

  def deletable_by?(user)
    user.present? and (self.user == user or user.admin?)
  end
  
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles

  validates :name, :presence => true

  def editable_by?(user)
   user.present? and user.admin?
  end

  def deletable_by?(user)
   user.present? and user.admin?
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

  
  
  validates :user, :presence => true
  validates :article, :presence => true
  validates :body, :presence => true, :length => { :maximum => 500 }

  def visible_to?(user)
    true
  end

  def deletable_by?(user)
    user.present? and user.admin?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :nickname
  
  has_many :articles
  has_many :comments
 
  validates :nickname, :presence => true, :uniqueness => true, :length => { :minimum => 3, :maximum => 15 }

  def admin?
    self.nickname == "Admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  respond_to :html
  before_filter :authenticate_user!, :except => [:index, :show]
  
  # GET /articles
  def index
    @articles = Kaminari.paginate_array(collection).page(params[:page]).per(6) 
    respond_with(@articles)
  end

  # GET /articles/1
  def show
    @article = Article.find(params[:id])
    authorize! :read, @article
    respond_with(@article)
  end

  # GET /articles/new
  def new
    @article = Article.new
    respond_with(@article)
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
    authorize! :update, @article
    respond_with(@article)
  end

  # POST /articles
  def create
    @article = current_user.articles.build(params[:article])
    respond_with(@article.tap(&:save))
  end

  # PUT /articles/1
  def update
    @article = Article.find(params[:id])
    authorize! :update, @article
    @article.update_attributes(params[:article])
    respond_with(@article)
  end

  # DELETE /articles/1
  def destroy
    @article = Article.find(params[:id])
    authorize! :destroy, @article
    @article.destroy
    respond_with(@article)
  end

  protected
  
  def parent
    return Category.find(params[:category_id]) if params.key?(:category_id)
  end
  def collection
    (parent.try(:articles) || Article).scoped
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  respond_to :html
  before_filter :authenticate_user!

  # GET /categories
  def index
    @categories = Category.all
    respond_with(@categories)
  end

  # GET /categories/1
  def show
    @category = Category.find(params[:id])
    respond_with(@category)
  end

  # GET /categories/new
  def new
    @category = Category.new
    respond_with(@category)
  end

  # GET /categoriess/1/edit
  def edit
    @category = Category.find(params[:id])
    authorize! :update, @category
    respond_with(@category)
  end

  # POST /categories
  def create
    @category = Category.new(params[:category])
    respond_with(@category.tap(&:save))
  end

  # PUT /categories/1
  def update
    @category = Category.find(params[:id])
    authorize! :update, @category
    @category.update_attributes(params[:category])
    respond_with(@category)
  end

  # DELETE /categories/1
  def destroy
    @category = Category.find(params[:id])
    authorize! :destroy, @category
    @category.destroy
    respond_with(@category)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html
  before_filter :authenticate_user! 

  
  
  def create
    article = Article.find(params[:article_id])
    @comment = article.comments.build(params[:comment])
    @comment.user = current_user
    
    respond_with(@comment.tap(&:save), :location => article) do |format|
    format.html {redirect_to article}
    end

  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    article = Article.find(params[:article_id])
    @comment = Comment.find(params[:id])
    authorize! :destroy, @comment
    @comment.destroy
    redirect_to(article)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article, :html => {:multipart=>true}) do |f| %>
<% if @article.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@article.errors.count, "λάθη") %> έκαναν αδύνατη την αποθήκευση του άρθρου:</h2>

<ul>
<% @article.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>


<div class="field">
<%= f.label :title, "Τίτλος" %><br />
<%= f.text_field :title %>
</div>
<div class="field">
<%= f.label :picture, "Εικόνα" %><br />
<%= f.file_field :picture %>
</div>
<div class="field">
<%= f.label :body, "Περιεχόμενο" %><br />
<%= f.text_area :body,:rows => 10, :cols => 80 %>
</div>
<div class="field">
<%= f.label :category, "Κατηγορία" %><br />
<%= f.select :category_id, Category.all.collect { |c| [c.name, c.id] } %>
</div>
<div class="actions">
<%= f.submit "Αποστολή" %>
</div>
<% end %>

app/views/articles/_list.html.erb
<ul>
  <% collection.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>

app/views/articles/edit.html.erb
<h1>Επεξεργασία Άρθρου</h1>

<%= render 'form' %>


<%= link_to 'Ανάγνωση', @article %> |
<%= link_to 'Πίσω', articles_path %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <div class="post">
    <h2 class="title"><%= article.title %></h2>
    <b>Κατηγορία:</b> <%= article.category.name %>
    <p class="date"><%= I18n.l(article.created_at, :format => :short) %></p>
    <div class="entry">
      <table>
       <tr>
         <td>
            <img><%= image_tag article.picture.url(:thumb) %></img>
         </td>
         <td>
         <dl>
          <dd><font color="#524B4D" size="3"><%= truncate(strip_tags(article.body),:length => 200) %></font></dd>
         </dl>
         </td>
       </tr>
      </table>
   <p class="links"><%= link_to "Σχόλια (#{article.comments.count})", article_path(article) %> <%= link_to 'Περισσότερα...', article, :class => "permalink" %></p>
    </div>
    <%= link_to 'Επεξεργασία', edit_article_path(article) if can? :update, article %> |
    <%= link_to 'Διαγραφή', article, :confirm => 'Είσαι βέβαιος?', :method => :delete if can? :destroy, article %>
  </div>
<% end %>
<%= paginate @articles %> 

app/views/articles/new.html.erb
<h1>Νέο άρθρο</h1>

<%= render 'form' %>

<%= link_to 'Πίσω', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<p font-size="25px">
  <font color="green" size="5px"><i><%= @article.title %></i></font>
</p>
<div>
 <%= image_tag @article.picture.url(:medium), :align => "left", :style => "padding-right:10px"%>
 <p><font color="#524B4D" size="3"><%= @article.body %></font></p>
</div>

<p>
  <b>Δημιουργήθηκε από:</b>
  <%= @article.user.nickname %>
</p>

<p>
  <b>Κατηγορία:</b>
  <%= link_to @article.category.name, category_articles_path(@article.category) %>
</p>

<%= link_to 'Επεξεργασία', edit_article_path(@article) if can? :update, @article %> 
<%= link_to 'Διαγραφή', @article, :confirm => 'Είσαι βέβαιος?', :method => :delete if can? :destroy, @article %> 
<%= link_to 'Πίσω', articles_path %>

<p><font color="green" size="3">Νέο Σχόλιο</font></p>
<%= render "comments/form" %>

<p><font color="green" size="3">Σχόλια</font></p>
<%= render "comments/list", :collection => @article.comments %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> εμπόδισαν την αποθήκευση της κατηγορίας:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_list.html.erb
<ul>
  <% collection.each do |category| %>
    <li><%= link_to category.name, category_articles_path(category) %></li>
  <% end %>
</ul>

app/views/categories/edit.html.erb
<h1>Επεξεργασία Κατηγορίας</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Πίσω', categories_path %>

app/views/categories/index.html.erb
<h1>Λίστα Κατηγοριών</h1>

<table>
  <tr>
    <th>Όνομα</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>Νέα Κατηγορία</h1>

<%= render 'form' %>

<%= link_to 'Πίσω', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Όνομα:</b>
  <%= @category.name %>
</p>


<%= link_to 'Επεξεργασία', edit_category_path(@category) %> |
<%= link_to 'Πίσω', categories_path %>

app/views/comments/_form.html.erb
<%= form_for [@article, Comment.new] do |f| %>
  <% if f.object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(f.object.errors.count, "λάθη") %> εμπόδισαν την αποθήκευση αυτού του σχολίου:</h2>

      <ul>
      <% f.object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :body,:size => "80x5"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_list.html.erb
<% if @article.comments.count == 0 %>
<p>Δεν υπάρχουν ακόμα σχόλια για αυτό το άρθρο.</br> Γράψτε τα δικά σας σχόλια στην παρακάτω φόρμα! </p>
<% else %>
<div style="background-color:#EDE7E4"><ul>
  <% collection.each do |comment| %>
    <div id="comments"> 	
    <li type="1">
      
      <p><%= comment.body %></br>
      <b>Δημιουργήθηκε από:</b> <%= comment.user.nickname %>
      <b>Στις: </b><%= I18n.l(comment.created_at, :format => :short) %></br>
      <%= link_to "Διαγραφή", article_comment_path(comment.article, comment), :method => :delete if can? :destroy, comment %></p>
      
    </li>
    </div>	
  <% end %>
</ul></div>
<% end %>

app/views/comments/edit.html.erb
<h1>Επεξεργασία Σχολίου</h1>

<%= render 'form' %>

<%= link_to 'Ανάγνωση', @comment %> |
<%= link_to 'Πίσω', comments_path %>

app/views/comments/index.html.erb
<h1>Λίστα Σχολίων</h1>

<table>
  <tr>
    <th>Άρθρο</th>
    <th>Χρήστης</th>
    <th>Περιεχόμενο</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.article_id %></td>
    <td><%= comment.user_id %></td>
    <td><%= comment.body %></td>
    <td><%= link_to 'Ανάγνωση', comment %></td>
    <td><%= link_to 'Επεξεργασία', edit_comment_path(comment) %></td>
    <td><%= link_to 'Διαγραφή', comment, :confirm => 'Είσαι βέβαιος?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Νέο Σχόλιο', new_comment_path %>

app/views/comments/new.html.erb
<h1>Νέο Σχόλιο</h1>

<%= render 'form' %>

<%= link_to 'Πίσω', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Άρθρο:</b>
  <%= @comment.article_id %>
</p>

<p>
  <b>Χρήστης:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Περιεχόμενο:</b>
  <%= @comment.body %>
</p>


<%= link_to 'Επεξεργασία', edit_comment_path(@comment) %> |
<%= link_to 'Πίσω', comments_path %>

app/views/commments/_form.html.erb
<%= form_for(@commment) do |f| %>
  <% if @commment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commment.errors.count, "error") %> prohibited this commment from being saved:</h2>

      <ul>
      <% @commment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article_id %><br />
    <%= f.text_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mynews</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <div id="menu">
      <ul>
        <li class="current_page_item"><%= link_to "Αρχική", root_path %> </li>
        
        <% if user_signed_in? %>
          <li><%= link_to "Προφίλ", user_path(current_user) %></li>
          <li><%= link_to "Αποσύνδεση", destroy_user_session_path %></li>
        <% else %>
          <li><%= link_to "Σύνδεση", new_user_session_path %></li>
          <li><%= link_to "Εγγραφή", new_user_registration_path %></li>
        <% end %>
        <li><%= link_to "Νέο Άρθρο", new_article_path %></li> 
        
      </ul>
    </div>
    <!-- end #menu -->
   
  </div>
  <!-- end #header -->
  
  <div id="logo">
    
  </div>
 
  <!-- end #logo -->
  <!-- end #header-wrapper -->

  <div id="page">
    <div id="content">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <!-- end #content -->
    <div id="sidebar">
      
      <ul>
       <% unless user_signed_in? %>
          <li>
            <h2>Σύνδεση</h2>
            <%= render "users/sessions/new" %>
          </li>
        <% end %>
        <li>
          <h2>Νέο Άρθρο</h2>
          <img src="/images/write1new.png" align="left"/><a href="/articles/new">Δημιουργήστε τα δικά σας άρθρα για την επικαιρότητα</a>
        </li>
        <li id="calendar">
          <h2>Κατηγορίες</h2>
          <%= render "categories/list", :collection => Category.all %>
        </li>
        <li>
          <h2>Άρθρα που σχολιάστηκαν</h2>
          <%= render "articles/list", :collection => Article.most_commented %>
        </li>
      </ul>
    </div>
    <!-- end #sidebar -->
    <div style="clear: both;">&nbsp;</div>
  </div>
  <!-- end #page -->

  <div id="footer">
    <p>Copyright (c) 2011 mynews.gr</p>
  </div>
  <!-- end #footer -->
</body>
</html>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Nickname</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.nickname %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_registration_path(user) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Σύνδεση", new_user_session_path %><br />
<% end -%>

<%- if controller_name != 'registrations' %>
  <%= link_to "Εγγραφή", new_user_registration_path %><br />
<% end -%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nickname:</b>
  <%= @user.nickname %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Τα άρθρα μου:</b>
  <%= render "articles/list", :collection => @user.articles %>
</p>

<%= link_to 'Επεξεργασία', edit_user_registration_path(@user) %> 